package me.ehsanmna.disaster.model.disaster;

public enum DisasterType {

    ACID_RAIN,DRAGON,FLOOD,HOT_POTATO,LIGHTING,METEOR,ZOMBIE,CUSTOME,WOLF_PLAYER,PVP, SWAP, GROUND, BLIND, HALF_HEALTH, NO_JUMP, TORNADO, RED_LIGHT_GREEN_LIGHT, GROUND_AWAY, WITHER

}
